application: birthdayfeed-hrd
version: 2
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /
  static_files: index.html
  upload: index.html

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /static
  static_dir: static

- url: /birthdayfeed.atom
  script: birthdayfeed.atom.py

- url: /birthdayfeed.ics
  script: birthdayfeed.ics.py

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /favicon.ico
  static_files: /static/birthdayfeed.png
  upload: /static/birthdayfeed.png
