services:
  app:
    image: ghcr.io/williamjacksn/birthdayfeed
    init: true
    ports:
      - 8080:8080
    volumes:
      - ./:/home/python/birthdayfeed

  fly:
    image: flyio/flyctl
    init: true
    volumes:
      - ./:/project
    working_dir: /project

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/birthdayfeed
    init: true
    volumes:
      - ./:/home/python/birthdayfeed
    working_dir: /home/python/birthdayfeed
