services:
  birthdayfeed:
    image: ghcr.io/williamjacksn/birthdayfeed
    init: true
    ports:
      - 8080:8080

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/williamjacksn/birthdayfeed
    init: true
    volumes:
      - ./:/home/python/birthdayfeed
    working_dir: /home/python/birthdayfeed
